-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. APPLICATIONS TABLE
-- Registered apps that can request consent
create table if not exists applications (
    app_id uuid primary key default uuid_generate_v4(),
    app_name text not null,
    owner_user_id uuid references auth.users(id), -- Link to Supabase Auth User
    verification_status text default 'pending' check (verification_status in ('pending', 'verified', 'rejected')),
    created_at timestamptz default now()
);

-- 2. PURPOSES TABLE
-- Standardized purposes for consent (Data Minimization principle)
create table if not exists purposes (
    purpose_code text primary key, -- e.g., 'CORE_FUNCTION', 'MARKETING'
    legal_basis text not null, -- e.g., 'CONSENT', 'CONTRACT', 'LEGITIMATE_INTEREST'
    description_plain text not null
);

-- Seed initial purposes
insert into purposes (purpose_code, legal_basis, description_plain) values
('CORE_FUNCTION', 'CONTRACT', 'Necessary for the core functionality of the application'),
('ANALYTICS', 'CONSENT', 'Anonymous usage analytics to improve service'),
('MARKETING', 'CONSENT', 'Sending promotional offers and updates');


-- 3. CONSENTS TABLE
-- The state of a user's consent for an app
create table if not exists consents (
    consent_id uuid primary key default uuid_generate_v4(),
    user_id uuid references auth.users(id) not null,
    app_id uuid references applications(app_id) not null,
    status text default 'active' check (status in ('active', 'revoked', 'expired')),
    granted_at timestamptz default now(),
    expiry_time timestamptz not null,
    revoked_at timestamptz
);

-- 4. CONSENT PURPOSES
-- Many-to-Many link between Consent and Purposes, defining scope
create table if not exists consent_purposes (
    id bigint generated by default as identity primary key,
    consent_id uuid references consents(consent_id) not null,
    purpose_code text references purposes(purpose_code) not null,
    data_categories text[] not null -- Array of strings e.g., ['email', 'location']
);

-- 5. CONSENT RECEIPTS
-- Immutable cryptographic proof of the consent grant
create table if not exists consent_receipts (
    receipt_id uuid primary key default uuid_generate_v4(),
    consent_id uuid references consents(consent_id) not null,
    signed_payload jsonb not null, -- The canonical JSON that was signed
    signature text not null, -- The cryptographic signature
    created_at timestamptz default now()
);

-- 6. AUDIT EVENTS
-- Append-only log for all actions (Grant, Revoke, Verify)
create table if not exists audit_events (
    event_id uuid primary key default uuid_generate_v4(),
    event_type text not null, -- 'CONSENT_GRANTED', 'CONSENT_REVOKED', 'RECEIPT_VERIFIED'
    actor_id uuid references auth.users(id), -- Who performed the action
    actor_type text not null, -- 'USER', 'APP', 'REGULATOR'
    event_payload jsonb not null, -- Context of the event
    timestamp timestamptz default now(),
    hash_prev text, -- Hash of the previous event (Hash Chain)
    hash_current text not null -- Hash of this event + prev_hash
);

-- RLS POLICIES (Example: Users can only see their own consents)
alter table consents enable row level security;

create policy "Users can view their own consents"
on consents for select
using (auth.uid() = user_id);

-- TODO: Add policies for App Admins and Regulators
